using Microsoft.AspNetCore.Mvc;
using Sandervanteinde.BlogApi.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Sandervanteinde.BlogApi.Controllers
{
    [Route("api/blogs")]
    public class BlogController : ControllerBase
    {
        private Blog[] Blogs = new[]
        {
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file"),
            new Blog(Guid.NewGuid(), "This is my blog title", "https://picsum.photos/800/300", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis alias id voluptas accusamus a ducimus ipsum eius omnis vero cupiditate quisquam quae unde, quis maxime nesciunt perspiciatis explicabo ab aliquam! Deserunt eveniet tenetur nihil eos laudantium fugiat doloremque excepturi magnam eum, et repudiandae. Eos suscipit doloribus quia saepe odio labore, culpa consectetur sunt nulla, eveniet itaque neque, incidunt enim laborum.", "# This will be the content of the markdown file")
        };
    
        [HttpGet]
        public ActionResult<IReadOnlyList<BlogListItem>> GetBlogs([FromQuery] BlogQuery query)
        {
            query = query.WithDefaultsFilled();
            var result = Blogs
                .Skip(query.StartIndex.Value)
                .Take(query.Amount.Value)
                .Select(b => new BlogListItem(b.Id, b.Title, b.LogoUrl, b.ShortDescription));
            return result.ToList();
        }
    }
}
