# Starts up all required services as docker containers
version: '3'

services:
  api:
    build: ../blog-api
    image: sandervanteinde/blog-api
    depends_on:
      - database
    environment:
      ConnectionStrings__BlogContext: "Server=database;Database=Blogs;User Id=postgres;Password=MyVeryStrongPassword1!;"
      VIRTUAL_HOST: api.localhost


  web:
    build: ../blog-website
    image: sandervanteinde/blog-website
    environment:
      VIRTUAL_HOST: localhost,www.localhost
      BLOG_APIURL: http://api.localhost/api
    depends_on: 
      - api

volumes:
  images:
    driver: local
