services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: MyVeryStrongPassword1!
    ports:
      - 5432:5432
    volumes:
      - sqlserver:/sqlserver
volumes:
  sqlserver:
    driver: local
