version: '3'

services:
  reverse:
    build: ../reverse-proxy
    image: sandervanteinde/reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - api
      - web
  api:
    build: ../blog-api
    image: sandervanteinde/blog-api
    depends_on:
      - database
    environment:
      ConnectionStrings__BlogContext: "Server=database;Database=Blogs;User Id=sa;Password=MyVeryStrongPassword1!;"
      ASPNETCORE_ENVIRONMENT: Development
  web:
    build: ../blog-website
    image: sandervanteinde/blog-website
    depends_on: 
      - api
