services:
  api:
    build: ../blog-api
    image: sandervanteinde/blog-api
    depends_on:
      - database
    environment:
      ConnectionStrings__BlogContext: "Server=database;Database=Blogs;User Id=sa;Password=MyVeryStrongPassword1!;"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5000:80
  web:
    build: ../blog-website
    image: sandervanteinde/blog-website
    ports:
      - 4200:80
    depends_on: 
      - api
