# Starts up all required services as docker containers
version: '3'

services:
  api:
    build: ../blog-api
    image: sandervanteinde/blog-api
    depends_on:
      - database
    ports:
      - 5000:80
    environment:
      ConnectionStrings__BlogContext: "Server=database;Database=Blogs;User Id=postgres;Password=MyVeryStrongPassword1!;"
      ASPNETCORE_ENVIRONMENT: Development
  web:
    build: ../blog-website
    image: sandervanteinde/blog-website
    ports:
      - 9000:80
    depends_on: 
      - api
